"""add invitations

Revision ID: d7ccb836c68e
Revises: ab92e517cd30
Create Date: 2026-08-08 14:46:33.026796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ccb836c68e'
down_revision: Union[str, Sequence[str], None] = 'ab92e517cd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','ACCEPTED','REJECTED','EXPIRED')", name='ck_invitation_status'),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invitation_publisher_status', 'invitations', ['publisher_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitation_publisher_status', table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
